// react/src/Grid.tsx
import type { Cell, Grid as GridType, VerifyContext } from "@gridz/core";
import { themeToCssVars } from "./theme.js";
import { useVerification } from "./useVerification.js";
import { GridCell } from "./GridCell.js";

export interface GridProps {
  grid: GridType;
  /** Verification context (e.g. a fixed `now` for tests). */
  verifyContext?: VerifyContext;
  /** Called when a verification badge is clicked (opens an attestation drawer in apps). */
  onBadgeClick?: (cell: Cell) => void;
  className?: string;
}

function headerName(grid: GridType): string {
  const alias = grid.cells.find((c) => c.key === "alias" && typeof c.value === "string");
  if (alias) return alias.value as string;
  if (grid.subject.display_name) return grid.subject.display_name;
  const did = grid.subject.ens ?? grid.subject.did;
  return did.length > 24 ? `${did.slice(0, 16)}…${did.slice(-6)}` : did;
}

/**
 * The reference Gridz renderer. Applies the theme as CSS variables, runs
 * client-side verification, and renders each visible cell with a verification
 * badge. Pixel-level aesthetic parity is validated by the Playwright suite
 * (see test/README.md) against the operator's own real Grid.
 */
export function Grid({ grid, verifyContext, onBadgeClick, className }: GridProps): JSX.Element {
  const verification = useVerification(grid, verifyContext);
  const visible = grid.cells.filter((c) => c.is_visible);

  return (
    <div
      className={`gridz-root${className ? ` ${className}` : ""}`}
      data-testid="gridz-root"
      data-root-status={verification.root}
      style={themeToCssVars(grid.theme)}
    >
      <header className="gridz-header">
        <h1 className="gridz-header__name">{headerName(grid)}</h1>
        <span className="gridz-header__subject" data-testid="gridz-subject-type">
          {grid.subject.type}
        </span>
        {grid.theme.show_gridz_badge === false ? null : (
          <span className="gridz-attribution" data-testid="gridz-attribution">
            Gridz
          </span>
        )}
      </header>
      <main className="gridz-grid" data-testid="gridz-grid">
        {visible.map((cell) => (
          <GridCell
            key={cell.id}
            cell={cell}
            status={verification.cells[cell.id] ?? "loading"}
            onBadgeClick={onBadgeClick}
          />
        ))}
      </main>
    </div>
  );
}

// svelte/src/Grid.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { verifyGrid, type Cell, type Grid, type VerifyContext } from "@gridz/core";
  import { TONES, headerName, themeVars, valueText, type BadgeStatus } from "./helpers.js";

  export let grid: Grid;
  export let verifyContext: VerifyContext | undefined = undefined;
  export let onBadgeClick: ((cell: Cell) => void) | undefined = undefined;

  let statuses: Record<string, BadgeStatus> = {};

  onMount(async () => {
    const result = await verifyGrid(grid, verifyContext);
    const next: Record<string, BadgeStatus> = {};
    for (const c of result.cells) next[c.id] = c.result.status;
    statuses = next;
  });

  $: styleStr = Object.entries(themeVars(grid.theme))
    .map(([k, v]) => `${k}:${v}`)
    .join(";");
  $: visible = grid.cells.filter((c) => c.is_visible);
</script>

<div class="gridz-root" data-testid="root" style={styleStr}>
  <header class="gridz-header">
    <span class="gridz-header__name" data-testid="name">{headerName(grid)}</span>
    <span class="gridz-header__subject">{grid.subject.type}</span>
  </header>
  <main class="gridz-grid" data-testid="grid">
    {#each visible as c (c.id)}
      {@const status = statuses[c.id] ?? "loading"}
      <div class="gridz-cell" data-testid="cell" data-key={c.key}>
        <div class="gridz-cell__head">
          <span class="gridz-cell__key">{c.key}</span>
          <button
            class="gridz-badge {TONES[status].tone}"
            data-testid="badge"
            data-status={status}
            data-tone={TONES[status].tone}
            aria-label={status}
            on:click={() => onBadgeClick?.(c)}
          >
            {TONES[status].icon}{status === "verified" && c.attestation.format === "eip712-oneclaw" ? "🔑" : ""}
          </button>
        </div>
        <div class="gridz-cell__body">{valueText(c.value)}</div>
      </div>
    {/each}
  </main>
</div>
